### ISSUE TITLE
Prevent Buffer.php to be always autoloaded

### ISSUE THREAD

**Issue by javiermarinros** [miguelbemartin/buffer-sdk-php#2]
Hola!

Could it be possible to update the package `composer.json` and replace the `"files"` key under `"autoload"` with `"classmap"`?

It should work the same and prevent the `Buffer.php` file to be loaded in every request.

Gracias!

**Comment by miguelbemartin** [comment]
Sure! could you open a PR with the changes, please?

**Comment by javiermarinros** [comment]
Sure! I just opened a PR, actually I did some tests and no special autoload entry for `"lib/Buffer.php"` is needed
